### ISSUE TITLE
Does not work properly in code-server

### ISSUE THREAD

**Issue by dingzhouL** [eclipse-cdt-cloud/theia-trace-extension#1105]
**Env**
```shell
code-server: 1.49.1
Trace Viewer for VSCode : v0.2.8
VSCode Trace Server : v0.2.3
jdk : 17.0.12
```
**Description**
I deployed a code-server using docker and installed Trace Viewer for VSCode and VSCode Trace Server. Here is my extension configuration:
```json
{
    "trace-server.traceserver.path": "/home/coder/trace/trace-compass-server/tracecompass-server",
    "trace-server.traceserver.arguments": "-vmargs -Dtraceserver.port=8081",
    "trace-compass.traceserver.url": "http://localhost:8081"
}
```
When the official recommended sample data is opened, it shows that trace-server opens fine, but there is no data in the webview.
![1724931526421](https://github.com/user-attachments/assets/f8ce0aea-891f-425b-8f3f-6d906643b66d)

**Comment by bhufmann** [comment]
The traces have to be accessible from the node that the trace server is running. Right now, opening the files uses direct file path and hence traces and trace server need to be co-located. Moreover, the vscode also needs to be on the same node. There has not been any implementation to upload traces from the trace viewer app to the node where the trace server runs. 

Alternatively, it's possible to use vscode-remote plug-in to run vscode on your laptop (for example) and the have traceserver/traces on a remote node. See here for more information about remote support: https://github.com/eclipse-cdt-cloud/vscode-trace-extension?tab=readme-ov-file#remote-ssh-support.

**Comment by dingzhouL** [comment]
Use the host's ip in code-server instead of localhost directly, and map traceserver's port if deploying in docker.
You can close this issue, thank you.

**Comment by marcdumais-work** [comment]
Thanks @dingzhouL for providing this follow-up.
