### ISSUE TITLE
req: Add searchable View List/Trace List

### ISSUE THREAD

**Issue by MatthewKhouzam** [eclipse-cdt-cloud/theia-trace-extension#1113]
Trace Compass's Trace Servers are getting more and more views. This is a positive, but now we must manage the views in a better way than just a simple list.

It would be good to have a search to find the type of view that we want to display.

This also applies to traces. I have 200+ traces in my trace server, so having a way to find which one I was viewing would speed up my workflows.

**Comment by ebugden** [comment]
+1 for flat list not being sufficient with a larger number of views!

Re view organization - There are a few existing issues that discuss view organization suggestions in a fair amount of detail #156, #157, and #158.
