### ISSUE TITLE
Selecting a row in the events table should sync the time graph to the row where where the corresponding event is visualized

### ISSUE THREAD

**Issue by mirsky-work** [eclipse-cdt-cloud/theia-trace-extension#219]
The time graph's Y-axis should be scrolled to the row that contains the corresponding element (state, marker). Would be nice to highlight it.
Was split from #111

**Comment by williamsyang-work** [comment]
This is functional, apart from a small oversight.
Oversight is documented [here](https://github.com/eclipse-cdt-cloud/theia-trace-extension/issues/743)
