### ISSUE TITLE
Packaging theia makes the browser build fail

### ISSUE THREAD

**Issue by arfio** [eclipse-cdt-cloud/theia-trace-extension#386]
To reproduce:
- yarn
- cd examples/electron/
- yarn package
- cd ../..
- yarn start:browser

"Error: Module did not self-register: '[...]/theia-trace-extension/node_modules/drivelist/build/Release/drivelist.node'."

**Comment by bhufmann** [comment]
I think this is not an issue anymore. There have been several updates in packaging since the time of reporting this issue. Feel free to re-open if needed.
