### ISSUE TITLE
Zoom  in selection range with "z"

### ISSUE THREAD

**Issue by IbrahimFradj** [eclipse-cdt-cloud/theia-trace-extension#427]
To facilitate the use of graphics and speed, I thought we could zoom in on the selection we have chosen with the "Z" button on the keyboard to get more details on the selection.

**Comment by ebugden** [comment]
@IbrahimFradj you could speak to @ssmagula about this. (They're working on defining good chart navigation.)

**Comment by ssmagula** [comment]
I'm promoting an enhancement to the Trace Viewer toolbar. Today this toolbar has some zoom and pan controls, and tomorrow will have other controls, as well. From user research, we know that keyboarding is essential to navigating charts and progressing from new user to intermediate user. So this proposed toolbar exposes a set of keyboard shortcuts via tooltips and a shortcut cheatsheet overlay. 

To view the cheatsheet the user would click a question mark icon in the toolbar (or press Ctrl-Shift-?) and it might look something like this: 

![image](https://user-images.githubusercontent.com/1106582/128044680-e76ff508-af4e-4b3c-a3c3-6ae54d0bfd48.png)

Zoom-heavy applications often use a series of shortcuts to go directly to specific zoom levels quickly. I followed the pattern where 0 is "default zoom" and then 1, 2... zooms in progressively: 

1. Return to default zoom is         Shift+0
2. Zoom to extent of selected is  Shift+1
3. Zoom to 10 ms (frame) is         Shift+2
4. Zoom to 1 ms (subframe) is     Shift+3
5. Zoom to slot ...

Re Z: To toggle a new zoom control on/off, I was thinking that pressing Z would do that. I'm still working on demonstrating how this might work. I'll post more later this week.

**Comment by IbrahimFradj** [comment]
What I'm trying to say here is that if I select a room (left click, drag), and I'm interested in that room and I want to zoom directly into that area, I press the z button to zoom in. 

**Example :**

![z zooming](https://user-images.githubusercontent.com/83769103/128253114-3679b97b-2cc1-4752-8eb4-0300af71cab9.gif)

**Comment by mirsky-work** [comment]
I agree the proposal can be a useful feature. On a related note, would be nice to also support zooming-in to a state by double-clicking it.

**Comment by williamsyang-work** [comment]
Working on implementing this feature 👍
