### ISSUE TITLE
Prebuilt AppImage application does not work properly

### ISSUE THREAD

**Issue by yoann-heitz** [eclipse-cdt-cloud/theia-trace-extension#560]
The prebuilt AppImage application is unable to start the trace server and can not open any trace.
When trying to open a trace in the Trace Viewer, a message indicates that the trace server can not be started because it was not found and that the correct path can be specified in the settings (I have java 11 installed).  
However, if I launch the trace server manually, it works.

Related to [392](https://github.com/theia-ide/theia-trace-extension/pull/392) and [352](https://github.com/theia-ide/theia-trace-extension/issues/352)

**Comment by bhufmann** [comment]
This is fixed. The pre-build example image is packages the latest trace server and it is able to start the server.
