### ISSUE TITLE
XY chart doesn't refresh its data model on resize

### ISSUE THREAD

**Issue by PatrickTasse** [eclipse-cdt-cloud/theia-trace-extension#726]
The XY chart doesn't react to resize events. When the chart is opened, or when the view range changes, it refreshes its data model.

If, at that moment, the chart width is 0, then it doesn't get a successful response from the trace-server and displays an error message in place of the chart: "Select a checkbox to see analysis results". When the chart is resized, this error message remains.

If, at that moment, the chart width is 5, it receives a data model from the trace-server with only 5 data points. When the chart is resized (e.g. to width=1000), it still displays only 5 data points.

The XY chart should refresh its data model when the chart width is changed. However this should be done through a debouncer to avoid overloading the server with many close requests.

**Comment by hriday-panchasara** [comment]
Picking up this issue
