### ISSUE TITLE
Support window dragging with mouse-middle drag in xy charts

### ISSUE THREAD

**Issue by bhufmann** [eclipse-cdt-cloud/theia-trace-extension#732]
In comparison to Time Graph charts, the xy-chart hasn't implemented the window drag with `middle mouse button` drag. This shall be added to the XY-charts. The cursor shall be update to the hand icon during this operation.

#702 added support for this operation using CTRL+mouse left button drag.

**Comment by hriday-panchasara** [comment]
Picking up this issue
