### ISSUE TITLE
Endless change of focus of trace viewer tabs when tabs are beside each other

### ISSUE THREAD

**Issue by bhufmann** [eclipse-cdt-cloud/theia-trace-extension#736]
After opening 2 traces, the trace viewer tabs are stacked behind each other. When moving one of the traces beside the other so that both are visible, then each tab gets focus and loses focus endlessly (see below). Because of this endless change of focus it's hard to  interact with one tab. The focus on the tab should be set by selection to one tab.

![bouncing-trace-container](https://user-images.githubusercontent.com/413424/164287003-57ea1499-96dc-4b96-a75d-13736e4b4b91.gif)

This needs to be fixed as per-requisite for #660.

**Comment by marco-miller** [comment]
I've been trying to Assign this issue to me, but GH seems like not caching or setting this properly so far.

**Comment by marco-miller** [comment]
> I've been trying to Assign this issue to me, but GH seems like not caching or setting this properly so far.

Fixed by now it seems.
