### ISSUE TITLE
Persist state of pinned view

### ISSUE THREAD

**Issue by hriday-panchasara** [eclipse-cdt-cloud/theia-trace-extension#762]
When pinning/unpinning a view, the xy and timeline charts lose state of their tree selections. Would be nice to persist the state of these charts when they are re-rendered due to pin/unpin action

**Comment by hriday-panchasara** [comment]
Working on this issue

**Comment by marco-miller** [comment]
> Working on this issue

You can assign yourself using `Assignees` on the right. I just did it for you. Thanks for picking this work up!
