### ISSUE TITLE
Support selection of time range using marker axis (timegraph-output-components)

### ISSUE THREAD

**Issue by bhufmann** [eclipse-cdt-cloud/theia-trace-extension#768]
The time graph output components supports showing a marker axis that can be filled with trace annotations provided by specific data providers. For example, lost event is one generic example. Other data providers can add their own domain specific markers as well.

It would be good that when selection a marker, that the time range of the marker is selected in all views.

**Comment by hriday-panchasara** [comment]
Picking up this issue
