### ISSUE TITLE
Add select all and deselect all in marker menu

### ISSUE THREAD

**Issue by bhufmann** [eclipse-cdt-cloud/theia-trace-extension#770]
The trace view has a menu to select which marker categories to visualize. Some domain specific data providers can have a long list of markers. A `Select all` and `Deselect all` menu item shall be added so that the use doesn't have click each category one by one.

![image](https://user-images.githubusercontent.com/413424/174825017-a5786071-77c3-4a92-8b57-4e04dce3884b.png)

**Comment by hriday-panchasara** [comment]
Picking up this issue
