### ISSUE TITLE
Provide output selector for overview view

### ISSUE THREAD

**Issue by bhufmann** [eclipse-cdt-cloud/theia-trace-extension#775]
With the addition of the Overview view (#745) it provides an overview of the trace using the histogram data provider. This ticket is to trace the addition of an dialog box so that user can select the XY data provider to use in the Overview view, because some user's are more interested in other characteristics, for example the CPU usage.

Add an button to the Overviews toolbar or open a dialog when pressing the `Show Overview` button and provide a list of data providers where user can select the data provider using a radio button.

**Comment by MatthewKhouzam** [comment]
This is done right?

**Comment by bhufmann** [comment]
Yes this one can be closed.
