### ISSUE TITLE
Select all series in the left tree of Histogram output by default

### ISSUE THREAD

**Issue by hoangphamEclipse** [eclipse-cdt-cloud/theia-trace-extension#786]
All series in the left tree of the Histogram output should be selected by default. This will improve the user experience for both the Histogram output and the trace overview.

**Comment by hriday-panchasara** [comment]
Picking up this issue

**Comment by bhufmann** [comment]
I think we can add a flag to the 'Entry' model of a row to indicate if a row is a supposed to be shown by default. This is full stack update. Not sure what the flag is supposed to be called, maybe `isDefault` or `showByDefault` or `selectByDefault` something else. 

In the front-end, after fetching the tree (fetchTree), the code can check all entries to select then ones where the flag is set and when the fetchTree() returns status COMPLETED then we can select the items and fetch the xy data accordingly:

in fetchTree() of abstract-xy-output-component.tsx 
```javascript
//...
               if (treeResponse.status === ResponseStatus.COMPLETED) {
                    const checkedSeries = this.getAllCheckedIds(treeResponse.model.entries);
                    this.setState({
                        outputStatus: treeResponse.status,
                        xyTree: treeResponse.model.entries,
                        checkedSeries,
                        columns
                    });
                } else {
                    this.setState({
                        outputStatus: treeResponse.status,
                        xyTree: treeResponse.model.entries,
                        columns
                    });
                }
//...
getAllCheckedIds(entries: Array<Entry>): Array<number> {
        const checkedSeries: number[] = [];
        for (const entry of entries) {
            if (entry.isDefault) {
                checkedSeries.push(entry.id);
            }
        }
        return checkedSeries;
    }
```

Then the data provider implementation in the back-end can set `isDefault` flag for the relevant entry.
