### ISSUE TITLE
Use the Theia backend to connect to trace server

### ISSUE THREAD

**Issue by tahini** [eclipse-cdt-cloud/theia-trace-extension#81]
Right now, the browser frontend directly connects to the trace server, which can be in another URL and cause CORS issues. The theia backend should be used to proxy the requests

**Comment by babyadoresorange** [comment]
Hm, I remember reading somewhere that this is intended. It seems that there was discussion regarding this mechanism ?

**Comment by ebugden** [comment]
Is this still an issue? Was this also fixed by @ankusht-work's PR #298?

**Comment by haoadoresorange** [comment]
I ran into this issue the other day when trying to connect to a remote trace-server. Should it be proxy through theia backend or this is more of an issue where trace-server should support CORS ?

**Comment by haoadoresorange** [comment]
> 
> 
> Is this still an issue? Was this also fixed by @ankusht-work's PR #298?
Afaik the answer is yes and then no.

**Comment by bhufmann** [comment]
Fixed by #976
