### ISSUE TITLE
Default data provider of Overview View is hard-coded

### ISSUE THREAD

**Issue by bhufmann** [eclipse-cdt-cloud/theia-trace-extension#840]
The default data provider ID of the `Overview View` is hard-coded to the histogram XY chart of the Trace Compass trace server. The default data provider ID should not be hard-coded, but should be configurable using a preference.

Note: The end-user has now way to know what the IDs of the available XY views are. So, the ID is probably not the best thing to have a preference for.

**Comment by hoangphamEclipse** [comment]
Hi @bhufmann, I am picking up this issue. I have a few questions that need clarification before I can make a proposal.

1. By preference, do you mean having the default view as an option in the Preference settings below:
![image](https://user-images.githubusercontent.com/92533264/194405381-5a45b3f0-a802-491f-baad-bbe28ee4f6b9.png)

2. Would the name of an XY view be a good preference? 

If we say yes to both of the above, then:

3.  If I remember correctly, all traces would have a Histogram view. Can you confirm this? If this is the case, `Histogram` is a great default value. 
4. Also, this would mean that the view name will be hard-coded in the `trace-server-preference.ts` file. Would this be OK?
5. If the user enter some view name that is not valid for a certain trace, would we default to the default `Histogram` view with some error message?
6. Personally, I am thinking of using either a list of available views that can be set as the default view or letting the users enter the name of the default view by themselves. I prefer the latter one. What do you think?

**Comment by bhufmann** [comment]
Thanks for picking this one up.

> Hi @bhufmann, I am picking up this issue. I have a few questions that need clarification before I can make a proposal.
> 
>     1. By preference, do you mean having the default view as an option in the Preference settings below:
>        ![image](https://user-images.githubusercontent.com/92533264/194405381-5a45b3f0-a802-491f-baad-bbe28ee4f6b9.png)
Yes, it would be a new trace viewer preference
> 
>     2. Would the name of an XY view be a good preference?
XY would not be a good name. The name should be related to the Overview view, maybe `Overview: Default`
> 
> 
> If we say yes to both of the above, then:
> 
>     3. If I remember correctly, all traces would have a Histogram view. Can you confirm this? If this is the case, `Histogram` is a great default value.
With Trace Compass based servers, there will be always a `Histogram view`. But for other server implementations not. Not exactly sure how preferences work in Theia. However, there could be a default one provided from the source code. But it is possible to changing the default one using the package.json of an Theia build. This should be possible for this preference. The `Trace Server: path` preference is created that way, so you can take it as example.
> 
>     4. Also, this would mean that the view name will be hard-coded in the `trace-server-preference.ts` file. Would this be OK?
Implement it similarly to the `Trace Server: path`
> 
>     5. If the user enter some view name that is not valid for a certain trace, would we default to the default `Histogram` view with some error message?
> 
Not sure if we need that level of complexity. You would have to do a back-end call to check if the name exists and if it is an xy chart. Maybe for initial version we, don't do that validation. If we get feedback, then we can implement it.

>     6. Personally, I am thinking of using either a list of available views that can be set as the default view or letting the users enter the name of the default view by themselves. I prefer the latter one. What do you think?
Let's use the latter one. I think it's easier to implement. This is useful for traces that don't have a histogram view. The histogram view can be the fallback one.

**Comment by hoangphamEclipse** [comment]
> > ```
> > 2. Would the name of an XY view be a good preference?
> > ```
> 
> 
> XY would not be a good name. The name should be related to the Overview view, maybe `Overview: Default`

What I meant to ask was the value of the `Overview: Default` preference. I would like to know if the value can be the name of any XY view. (e.g. the value would be something like `Histogram`, or `Disk IO View`.





> Implement it similarly to the `Trace Server: path`

You mean as in the photo below right? 
![image](https://user-images.githubusercontent.com/92533264/194580360-22d08f5b-9c8a-4aa5-bf54-371c976842bf.png)

**Comment by bhufmann** [comment]
> > > ```
> > > 2. Would the name of an XY view be a good preference?
> > > ```
> > 
> > 
> > XY would not be a good name. The name should be related to the Overview view, maybe `Overview: Default`
> 
> What I meant to ask was the value of the `Overview: Default` preference. I would like to know if the value can be the name of any XY view. (e.g. the value would be something like `Histogram`, or `Disk IO View`.

I think we can only use the name of the view. The data provider ID is internal to the tool and it's not exposed to the end user even if the ID would be a more reliable choice.
> 
> > Implement it similarly to the `Trace Server: path`
> 
> You mean as in the photo below right? ![image](https://user-images.githubusercontent.com/92533264/194580360-22d08f5b-9c8a-4aa5-bf54-371c976842bf.png)

Yes
