### ISSUE TITLE
Events Table search filter text gets lost when scrolling horizontally

### ISSUE THREAD

**Issue by bhufmann** [eclipse-cdt-cloud/theia-trace-extension#841]
Events Table search filter text gets lost when scrolling horizontally in the table

![table-search-text-scroll-bug](https://user-images.githubusercontent.com/413424/191975488-059c0450-eff0-4bfc-888c-4d35b4135a78.gif)

**Comment by hriday-panchasara** [comment]
Picked up by Traviz
