### ISSUE TITLE
Theia trace extension version numbers go "backwards" sometimes

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-cdt-cloud/theia-trace-extension#842]
The current Theia Trace Extension version numbers go backwards sometimes.

e.g. at the moment the most recent `@next` is version `0.2.0-next.88a3e53.0` (commit 88a3e53), but there is an older version `0.2.0-next.ff00759.0` (commit ff00759), so if you do a `yarn upgrade` you can go "backwards" from `0.2.0-next.88a3e53.0` to `0.2.0-next.ff00759.0`

cdt-gdb-adapter had a similar problem once upon a time - https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/issues/133#issuecomment-562882017 and the way I fixed it was including date in URL like below:

```sh
yarn version  --no-git-tag-version --prerelease --preid=next.$(date -u "+%Y%m%d%H%M%S").$(git rev-parse --short HEAD)
```

**Comment by bhufmann** [comment]
Thanks for reporting this. I was not aware of it and expected that yarn would be able to calculate the correct next version.
