### ISSUE TITLE
Issue with opening Keyboard Shortcuts Dialog

### ISSUE THREAD

**Issue by hriday-panchasara** [eclipse-cdt-cloud/theia-trace-extension#853]
Observed the following issue when opening the Keyboard Shortcuts Dialog through the Toolbar Menu or Command Palette:
![Screen Shot 2022-10-12 at 3 55 23 PM](https://user-images.githubusercontent.com/92893187/195702035-595f099b-1836-419e-898c-722fd52917a3.png)

Here's the error logged to the console:
![Screen Shot 2022-10-12 at 3 55 43 PM](https://user-images.githubusercontent.com/92893187/195702214-daebcf37-6f16-487c-9c99-242569786f75.png)

**Comment by hriday-panchasara** [comment]
Picking up this issue

**Comment by bhufmann** [comment]
@hriday-panchasara I'm running the extension from master of today, but I don't get the error. I press `F1`, then type `Trace Viewer Keyboard and Mouse Short-cuts` and I don't get this error. What steps are you doing?

**Comment by hriday-panchasara** [comment]
> @hriday-panchasara I'm running the extension from master of today, but I don't get the error. I press `F1`, then type `Trace Viewer Keyboard and Mouse Short-cuts` and I don't get this error. What steps are you doing?

If you close the modal using the 'x' button on the top-right and try to open it again it shows this error.

**Comment by bhufmann** [comment]
> > @hriday-panchasara I'm running the extension from master of today, but I don't get the error. I press `F1`, then type `Trace Viewer Keyboard and Mouse Short-cuts` and I don't get this error. What steps are you doing?
> 
> If you close the modal using the 'x' button on the top-right and try to open it again it shows this error.

Thanks for the info. I was able to reproduce and verify that #922 fixes the issue.
