### ISSUE TITLE
Support Shift + up/down in table-output-component

### ISSUE THREAD

**Issue by hriday-panchasara** [eclipse-cdt-cloud/theia-trace-extension#854]
With the upgrade of AgGrid in https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/813 looks like the user is not able to select multiple rows through Shift + up/down

**Comment by hoangphamEclipse** [comment]
Hello Hriday, I tested this out and looks like the user needs to focus a cell (so that it has the blue border) before Shifting up/down. If I focus on a cell, it works fine. Can you double check this?

**Comment by hoangphamEclipse** [comment]
Closing this issue since confirmed that this is not a bug.
