### ISSUE TITLE
Issue with 'Show Trace overview' toolbar button

### ISSUE THREAD

**Issue by hriday-panchasara** [eclipse-cdt-cloud/theia-trace-extension#856]
[Screen Recording 2022-10-17 at 4.59.06 PM.webm](https://user-images.githubusercontent.com/92893187/196291984-5cc1a6a3-6962-4cd3-8574-6b3906aed996.webm)

**Comment by williamsyang-work** [comment]
@marco-miller opening the overview opens the overview in every opened trace.  It should only open the overview in the current trace a user is working in.

**Comment by hoangphamEclipse** [comment]
I am picking up this issue.
